# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TigrisCli < Formula
  desc "Tigris is a modern, scalable backend for building real-time websites and apps."
  homepage "https://docs.tigrisdata.com"
  version "1.0.0-beta.20"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tigrisdata/tigris-cli/releases/download/v1.0.0-beta.20/tigris_1.0.0-beta.20_darwin_arm64.tar.gz"
      sha256 "9121151eec61977246c38f41b0f09ee3da70571a2366c5e39a95a0ec82d4499a"

      def install
        bin.install "tigris"
        bash_completion.install "completion/bash/tigris" => "tigris"
        zsh_completion.install "completion/zsh/_tigris" => "_tigris"
        fish_completion.install "completion/fish/tigris"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tigrisdata/tigris-cli/releases/download/v1.0.0-beta.20/tigris_1.0.0-beta.20_darwin_amd64.tar.gz"
      sha256 "64d7c5e56344b1d553f378d2498bd884f3223390f5d9837f35a9cec386a81fe8"

      def install
        bin.install "tigris"
        bash_completion.install "completion/bash/tigris" => "tigris"
        zsh_completion.install "completion/zsh/_tigris" => "_tigris"
        fish_completion.install "completion/fish/tigris"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tigrisdata/tigris-cli/releases/download/v1.0.0-beta.20/tigris_1.0.0-beta.20_linux_arm64.tar.gz"
      sha256 "357721efb06e1ab18e5e8f86d590a661ccf9d63e93e30dd18decb683a46fad3f"

      def install
        bin.install "tigris"
        bash_completion.install "completion/bash/tigris" => "tigris"
        zsh_completion.install "completion/zsh/_tigris" => "_tigris"
        fish_completion.install "completion/fish/tigris"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tigrisdata/tigris-cli/releases/download/v1.0.0-beta.20/tigris_1.0.0-beta.20_linux_amd64.tar.gz"
      sha256 "a240a0885896572228bce7a5eb33f6ca0eb6dfc1c28451bb4203b65fb8a84831"

      def install
        bin.install "tigris"
        bash_completion.install "completion/bash/tigris" => "tigris"
        zsh_completion.install "completion/zsh/_tigris" => "_tigris"
        fish_completion.install "completion/fish/tigris"
      end
    end
  end
end
