# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TigrisCli < Formula
  desc "Tigris is a modern, scalable backend for building real-time websites and apps."
  homepage "https://docs.tigrisdata.com"
  version "1.0.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/tigrisdata/tigris-cli/releases/download/v1.0.3/tigris_1.0.3_darwin_arm64.tar.gz"
      sha256 "c3cd8b9a9d3b06b2fb918248031fe626256f947d57ae19e88b3175ae44085a53"

      def install
        bin.install "tigris"
        bash_completion.install "completion/bash/tigris" => "tigris"
        zsh_completion.install "completion/zsh/_tigris" => "_tigris"
        fish_completion.install "completion/fish/tigris"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/tigrisdata/tigris-cli/releases/download/v1.0.3/tigris_1.0.3_darwin_amd64.tar.gz"
      sha256 "d728cf7b7076b266496e5cecd5cb9194d3418000341ec1cf01a94d28acee611c"

      def install
        bin.install "tigris"
        bash_completion.install "completion/bash/tigris" => "tigris"
        zsh_completion.install "completion/zsh/_tigris" => "_tigris"
        fish_completion.install "completion/fish/tigris"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tigrisdata/tigris-cli/releases/download/v1.0.3/tigris_1.0.3_linux_amd64.tar.gz"
      sha256 "9f8b04140347d8283efe190e6f11449b9ff87d12104a1b7ac9c99d3f999599b8"

      def install
        bin.install "tigris"
        bash_completion.install "completion/bash/tigris" => "tigris"
        zsh_completion.install "completion/zsh/_tigris" => "_tigris"
        fish_completion.install "completion/fish/tigris"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tigrisdata/tigris-cli/releases/download/v1.0.3/tigris_1.0.3_linux_arm64.tar.gz"
      sha256 "19ca22ed01fef253df38f1a40905e2724918f96e4a1839dde6cf95dbdda21896"

      def install
        bin.install "tigris"
        bash_completion.install "completion/bash/tigris" => "tigris"
        zsh_completion.install "completion/zsh/_tigris" => "_tigris"
        fish_completion.install "completion/fish/tigris"
      end
    end
  end
end
